- product: R1
  versions:
  - version: V10
    type: full_product
    web_page_template: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/dark_template.html
    video: https://player.vimeo.com/video/867609894?h=17434b55fd
    picture: 
      - https://raw.githubusercontent.com/tomrodinger/line_following_robot/main/Pictures/V10/top1.jpg
      - https://m.media-amazon.com/images/I/51DBd7O6GEL._AC_UF894,1000_QL80_.jpg
    description: This is a robot that follows a line. Multiple robots can share a track, communicate, and avoid collisions.
    schematic: https://raw.githubusercontent.com/tomrodinger/line_following_robot/main/PCB/V10/schematic.pdf
    user_manual: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R1/V1/user-manual.pdf
    tutorial: https://servo-tutorial.netlify.app/
    github: https://github.com/tomrodinger/line_following_robot/tree/main/PCB/V10
    firmwares:
    - version: "0.2.3"
      compatibility: 0
      date: September 9, 2021
      description: Initial firmware for the Robot
      url: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R1/firmware/0.2.3.firmware
      sha256: 43f6df3f42ae0582b1331c3ebc3eec1662dc2a7740039b04128bb06d5931dac9
    - version: "0.2.4"
      compatibility: 0
      date: September 2, 2022
      description: Robot can now follow a line. No audio playing.
      url: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R1/firmware/0.2.4.firmware
      sha256: 42bc5b4df78ad032ab15f4badfa974cfbd40519554dcdd277b5994c3bcc4ed25
    - version: "0.2.5"
      compatibility: 0
      date: September 29, 2022
      description: Fixed oject detection bug.
      url: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R1/firmware/0.2.5.firmware
      sha256: b1374c3d764bb456661480f8d7fb871967202f30528dc16ed80daefd17b34945
  - version: V11
    type: full_product
    web_page_template: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/dark_template.html
    picture: https://raw.githubusercontent.com/tomrodinger/line_following_robot/main/Pictures/V11/top2.jpg
    description: This is a robot that follows a line. Multiple robots can share a track, communicate, and avoid collisions.
    schematic: https://raw.githubusercontent.com/tomrodinger/line_following_robot/main/PCB/V11/schematic.pdf
    user_manual: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R1/V1/user-manual.pdf
    tutorial: https://servo-tutorial.netlify.app/
    github: https://github.com/tomrodinger/line_following_robot/tree/main/PCB/V11
    firmwares:
    - version: "0.2.3"
      compatibility: 0
      date: September 9, 2021
      description: Initial firmware for the Robot
      url: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R1/firmware/0.2.3.firmware
      sha256: 43f6df3f42ae0582b1331c3ebc3eec1662dc2a7740039b04128bb06d5931dac9
    - version: "0.2.4"
      compatibility: 0
      date: September 2, 2022
      description: Robot can now follow a line. No audio playing.
      url: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R1/firmware/0.2.4.firmware
      sha256: 42bc5b4df78ad032ab15f4badfa974cfbd40519554dcdd277b5994c3bcc4ed25
    - version: "0.2.5"
      compatibility: 0
      date: September 29, 2022
      description: Fixed oject detection bug.
      url: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R1/firmware/0.2.5.firmware
      sha256: b1374c3d764bb456661480f8d7fb871967202f30528dc16ed80daefd17b34945
  - version: V12
    type: full_product
    web_page_template: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/dark_template.html
    picture: https://raw.githubusercontent.com/tomrodinger/line_following_robot/main/Pictures/V12/top2.jpg
    description: This is a robot that follows a line. Multiple robots can share a track, communicate, and avoid collisions with each other.
    schematic: https://raw.githubusercontent.com/tomrodinger/line_following_robot/main/PCB/V12/schematic.pdf
    user_manual: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R1/V1/user-manual.pdf
    tutorial: https://servo-tutorial.netlify.app/
    github: https://github.com/tomrodinger/line_following_robot/tree/main/PCB/V12
    firmwares:
    - version: "0.2.3"
      compatibility: 0
      date: September 9, 2021
      description: Initial firmware for the Robot
      url: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R1/firmware/0.2.3.firmware
      sha256: 43f6df3f42ae0582b1331c3ebc3eec1662dc2a7740039b04128bb06d5931dac9
    - version: "0.2.4"
      compatibility: 0
      date: September 2, 2022
      description: Robot can now follow a line. No audio playing.
      url: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R1/firmware/0.2.4.firmware
      sha256: 42bc5b4df78ad032ab15f4badfa974cfbd40519554dcdd277b5994c3bcc4ed25
    - version: "0.2.5"
      compatibility: 0
      date: September 29, 2022
      description: Fixed oject detection bug.
      url: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R1/firmware/0.2.5.firmware
      sha256: b1374c3d764bb456661480f8d7fb871967202f30528dc16ed80daefd17b34945
